//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mossrecru.iOS.app.ifs.aero {
    using System.Xml.Serialization;
    using System.Diagnostics;
    using System.Web.Services;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("VisualStudio", "8.10.6.10")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding", Namespace="http://tempuri.org/")]
    public partial class RecruitmentService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCandidatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTechnologiesOperationCompleted;
        
        /// <remarks/>
        public RecruitmentService() {
            this.Url = "https://app.ifs.aero/EternalBlue/recruitment.asmx";
        }
        
        public RecruitmentService(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        public event GetCandidatesCompletedEventHandler GetCandidatesCompleted;
        
        /// <remarks/>
        public event GetTechnologiesCompletedEventHandler GetTechnologiesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IRecruitmentService/GetCandidates", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/EternalBlue.Models")]
        public Candidate[] GetCandidates() {
            object[] results = this.Invoke("GetCandidates", new object[0]);
            return ((Candidate[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCandidatesAsync() {
            this.GetCandidatesAsync(null);
        }
        
        /// <remarks/>
        public void GetCandidatesAsync(object userState) {
            if ((this.GetCandidatesOperationCompleted == null)) {
                this.GetCandidatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCandidatesOperationCompleted);
            }
            this.InvokeAsync("GetCandidates", new object[0], this.GetCandidatesOperationCompleted, userState);
        }
        
        private void OnGetCandidatesOperationCompleted(object arg) {
            if ((this.GetCandidatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCandidatesCompleted(this, new GetCandidatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IRecruitmentService/GetTechnologies", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/EternalBlue.Models")]
        public Technology[] GetTechnologies() {
            object[] results = this.Invoke("GetTechnologies", new object[0]);
            return ((Technology[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTechnologiesAsync() {
            this.GetTechnologiesAsync(null);
        }
        
        /// <remarks/>
        public void GetTechnologiesAsync(object userState) {
            if ((this.GetTechnologiesOperationCompleted == null)) {
                this.GetTechnologiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTechnologiesOperationCompleted);
            }
            this.InvokeAsync("GetTechnologies", new object[0], this.GetTechnologiesOperationCompleted, userState);
        }
        
        private void OnGetTechnologiesOperationCompleted(object arg) {
            if ((this.GetTechnologiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTechnologiesCompleted(this, new GetTechnologiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("VisualStudio", "8.10.6.10")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/EternalBlue.Models")]
    public partial class Candidate {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Barcode;
        
        /// <remarks/>
        public bool CanSwim;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CanSwimSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CandidateId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Dad;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Skill[] Experience;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FavoriteMusicGenre;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FirstName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FullName;
        
        /// <remarks/>
        public Gender Gender;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LastName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Mom;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProfilePicture;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("VisualStudio", "8.10.6.10")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/EternalBlue.Models")]
    public partial class Skill {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TechnologyId;
        
        /// <remarks/>
        public int YearsOfExperience;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool YearsOfExperienceSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("VisualStudio", "8.10.6.10")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/EternalBlue.Models")]
    public partial class Technology {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Guid;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("VisualStudio", "8.10.6.10")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Bogus.DataSets")]
    public enum Gender {
        
        /// <remarks/>
        Male,
        
        /// <remarks/>
        Female,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("VisualStudio", "8.10.6.10")]
    public delegate void GetCandidatesCompletedEventHandler(object sender, GetCandidatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("VisualStudio", "8.10.6.10")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCandidatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCandidatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Candidate[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Candidate[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("VisualStudio", "8.10.6.10")]
    public delegate void GetTechnologiesCompletedEventHandler(object sender, GetTechnologiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("VisualStudio", "8.10.6.10")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTechnologiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTechnologiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Technology[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Technology[])(this.results[0]));
            }
        }
    }
}
